name: CI Pipeline
on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
env:
  USE_DOCKER: true
jobs:
  test:
    runs-on: ["{% raw %}${{ matrix.os }}{% endraw %}"]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
          python -m pip install -U pip docker-compose

      - name: Unit tests
        run: |
          make test

      - name: Publish coverage to codecov.io.
        uses: codecov/codecov-action@v2
        if: ${% raw %}{{ !env.ACT }}{% endraw %}
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          verbose: true
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
          python -m pip install -U pip docker-compose

      - name: Run linters.
        run: |
          make lint
  check_cc_and_requirements:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Check that requirements are up-to-date.
        run: |
          make check-requirements

      - name: Check that this project is up-to-date with cookiecutter.
        run: |
          make check-cc

  publish:
    runs-on: [ubuntu-latest]
    needs:
      - check_cc_and_requirements
      - lint
      - test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install pypa/build
        run: |
          python -m pip install --user build setuptools_scm

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Build wheels
        run: |
          python setup.py sdist

      - name: Publish distribution to PyPI
        if: github.repository == '{{ cookiecutter.git_org_name }}/{{ cookiecutter.git_repo_name }}' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${% raw %}{{ secrets.PYPI_API_TOKEN }}{% endraw %}
